//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestServicioGestionSolicitudes.ApoderadoWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Apoderado", Namespace="http://schemas.datacontract.org/2004/07/ServicioGestionSolicitudes.Dominio")]
    [System.SerializableAttribute()]
    public partial class Apoderado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroCelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroDniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentescoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroCelular {
            get {
                return this.NroCelularField;
            }
            set {
                if ((object.ReferenceEquals(this.NroCelularField, value) != true)) {
                    this.NroCelularField = value;
                    this.RaisePropertyChanged("NroCelular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroDni {
            get {
                return this.NroDniField;
            }
            set {
                if ((object.ReferenceEquals(this.NroDniField, value) != true)) {
                    this.NroDniField = value;
                    this.RaisePropertyChanged("NroDni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parentesco {
            get {
                return this.ParentescoField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentescoField, value) != true)) {
                    this.ParentescoField = value;
                    this.RaisePropertyChanged("Parentesco");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManejadorException", Namespace="http://schemas.datacontract.org/2004/07/ServicioGestionSolicitudes.Errores")]
    [System.SerializableAttribute()]
    public partial class ManejadorException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ApoderadoWS.IApoderadoService")]
    public interface IApoderadoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApoderadoService/Obtener", ReplyAction="http://tempuri.org/IApoderadoService/ObtenerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TestServicioGestionSolicitudes.ApoderadoWS.ManejadorException), Action="http://tempuri.org/IApoderadoService/ObtenerManejadorExceptionFault", Name="ManejadorException", Namespace="http://schemas.datacontract.org/2004/07/ServicioGestionSolicitudes.Errores")]
        TestServicioGestionSolicitudes.ApoderadoWS.Apoderado Obtener(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApoderadoService/Obtener", ReplyAction="http://tempuri.org/IApoderadoService/ObtenerResponse")]
        System.Threading.Tasks.Task<TestServicioGestionSolicitudes.ApoderadoWS.Apoderado> ObtenerAsync(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApoderadoService/Crear", ReplyAction="http://tempuri.org/IApoderadoService/CrearResponse")]
        TestServicioGestionSolicitudes.ApoderadoWS.Apoderado Crear([System.ServiceModel.MessageParameterAttribute(Name="Crear")] TestServicioGestionSolicitudes.ApoderadoWS.Apoderado Crear1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApoderadoService/Crear", ReplyAction="http://tempuri.org/IApoderadoService/CrearResponse")]
        System.Threading.Tasks.Task<TestServicioGestionSolicitudes.ApoderadoWS.Apoderado> CrearAsync(TestServicioGestionSolicitudes.ApoderadoWS.Apoderado Crear);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IApoderadoServiceChannel : TestServicioGestionSolicitudes.ApoderadoWS.IApoderadoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApoderadoServiceClient : System.ServiceModel.ClientBase<TestServicioGestionSolicitudes.ApoderadoWS.IApoderadoService>, TestServicioGestionSolicitudes.ApoderadoWS.IApoderadoService {
        
        public ApoderadoServiceClient() {
        }
        
        public ApoderadoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApoderadoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApoderadoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApoderadoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestServicioGestionSolicitudes.ApoderadoWS.Apoderado Obtener(string dni) {
            return base.Channel.Obtener(dni);
        }
        
        public System.Threading.Tasks.Task<TestServicioGestionSolicitudes.ApoderadoWS.Apoderado> ObtenerAsync(string dni) {
            return base.Channel.ObtenerAsync(dni);
        }
        
        public TestServicioGestionSolicitudes.ApoderadoWS.Apoderado Crear(TestServicioGestionSolicitudes.ApoderadoWS.Apoderado Crear1) {
            return base.Channel.Crear(Crear1);
        }
        
        public System.Threading.Tasks.Task<TestServicioGestionSolicitudes.ApoderadoWS.Apoderado> CrearAsync(TestServicioGestionSolicitudes.ApoderadoWS.Apoderado Crear) {
            return base.Channel.CrearAsync(Crear);
        }
    }
}
