//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDePrematricula.NivelesServWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Niveles", Namespace="http://schemas.datacontract.org/2004/07/ServicioGestionSolicitudes.Dominio")]
    [System.SerializableAttribute()]
    public partial class Niveles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnhoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DisponibleVacantesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdNivelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NivelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalVacantesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TurnoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Anho {
            get {
                return this.AnhoField;
            }
            set {
                if ((this.AnhoField.Equals(value) != true)) {
                    this.AnhoField = value;
                    this.RaisePropertyChanged("Anho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisponibleVacantes {
            get {
                return this.DisponibleVacantesField;
            }
            set {
                if ((this.DisponibleVacantesField.Equals(value) != true)) {
                    this.DisponibleVacantesField = value;
                    this.RaisePropertyChanged("DisponibleVacantes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grado {
            get {
                return this.GradoField;
            }
            set {
                if ((object.ReferenceEquals(this.GradoField, value) != true)) {
                    this.GradoField = value;
                    this.RaisePropertyChanged("Grado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdNivel {
            get {
                return this.IdNivelField;
            }
            set {
                if ((this.IdNivelField.Equals(value) != true)) {
                    this.IdNivelField = value;
                    this.RaisePropertyChanged("IdNivel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nivel {
            get {
                return this.NivelField;
            }
            set {
                if ((object.ReferenceEquals(this.NivelField, value) != true)) {
                    this.NivelField = value;
                    this.RaisePropertyChanged("Nivel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Seccion {
            get {
                return this.SeccionField;
            }
            set {
                if ((object.ReferenceEquals(this.SeccionField, value) != true)) {
                    this.SeccionField = value;
                    this.RaisePropertyChanged("Seccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalVacantes {
            get {
                return this.TotalVacantesField;
            }
            set {
                if ((this.TotalVacantesField.Equals(value) != true)) {
                    this.TotalVacantesField = value;
                    this.RaisePropertyChanged("TotalVacantes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Turno {
            get {
                return this.TurnoField;
            }
            set {
                if ((object.ReferenceEquals(this.TurnoField, value) != true)) {
                    this.TurnoField = value;
                    this.RaisePropertyChanged("Turno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManejadorException", Namespace="http://schemas.datacontract.org/2004/07/ServicioGestionSolicitudes.Errores")]
    [System.SerializableAttribute()]
    public partial class ManejadorException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NivelesServWS.INivelesService")]
    public interface INivelesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INivelesService/Obtener", ReplyAction="http://tempuri.org/INivelesService/ObtenerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SistemaDePrematricula.NivelesServWS.ManejadorException), Action="http://tempuri.org/INivelesService/ObtenerManejadorExceptionFault", Name="ManejadorException", Namespace="http://schemas.datacontract.org/2004/07/ServicioGestionSolicitudes.Errores")]
        SistemaDePrematricula.NivelesServWS.Niveles Obtener(string Nivel, string Grado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INivelesService/Obtener", ReplyAction="http://tempuri.org/INivelesService/ObtenerResponse")]
        System.Threading.Tasks.Task<SistemaDePrematricula.NivelesServWS.Niveles> ObtenerAsync(string Nivel, string Grado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INivelesServiceChannel : SistemaDePrematricula.NivelesServWS.INivelesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NivelesServiceClient : System.ServiceModel.ClientBase<SistemaDePrematricula.NivelesServWS.INivelesService>, SistemaDePrematricula.NivelesServWS.INivelesService {
        
        public NivelesServiceClient() {
        }
        
        public NivelesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NivelesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NivelesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NivelesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SistemaDePrematricula.NivelesServWS.Niveles Obtener(string Nivel, string Grado) {
            return base.Channel.Obtener(Nivel, Grado);
        }
        
        public System.Threading.Tasks.Task<SistemaDePrematricula.NivelesServWS.Niveles> ObtenerAsync(string Nivel, string Grado) {
            return base.Channel.ObtenerAsync(Nivel, Grado);
        }
    }
}
